#!/bin/bash
# Configure InterMine properties for RDS connection
# This script modifies the InterMine properties file to connect to AWS RDS

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

log() {
    echo -e "${BLUE}[CONFIGURE] $1${NC}"
}

error() {
    echo -e "${RED}[CONFIGURE] ERROR: $1${NC}"
}

success() {
    echo -e "${GREEN}[CONFIGURE] $1${NC}"
}

# Paths
TEMPLATE_FILE="$HOME/alliancemine/alliancemine.properties.template"
PROPERTIES_FILE="$HOME/alliancemine/alliancemine.properties"
INTERMINE_PROPERTIES="$HOME/.intermine/alliancemine.properties"

# Function to backup original properties
backup_properties() {
    if [[ -f "$PROPERTIES_FILE" ]]; then
        cp "$PROPERTIES_FILE" "$PROPERTIES_FILE.backup.$(date +%Y%m%d_%H%M%S)"
        log "Backed up existing properties file"
    fi
}

# Function to create RDS-optimized properties file
create_rds_properties() {
    log "Creating RDS-optimized properties file..."
    
    # Start with template
    cp "$TEMPLATE_FILE" "$PROPERTIES_FILE"
    
    # Database connection settings for RDS
    cat >> "$PROPERTIES_FILE" <<EOF

# ========================================
# RDS Database Configuration
# ========================================
# Generated by configure-rds.sh on $(date)

# Main production database (RDS)
db.production.datasource.class=com.zaxxer.hikari.HikariDataSource
db.production.datasource.dataSourceClassName=org.postgresql.ds.PGSimpleDataSource
db.production.datasource.dataSourceProperties.serverName=${DB_HOST}
db.production.datasource.dataSourceProperties.portNumber=${DB_PORT}
db.production.datasource.dataSourceProperties.databaseName=${DB_NAME}
db.production.datasource.dataSourceProperties.user=${DB_USER}
db.production.datasource.dataSourceProperties.password=${DB_PASSWORD}
db.production.datasource.dataSourceProperties.ssl=false
db.production.datasource.maximumPoolSize=20
db.production.datasource.connectionTimeout=30000
db.production.datasource.idleTimeout=600000
db.production.datasource.maxLifetime=1800000
db.production.driver=org.postgresql.Driver
db.production.platform=PostgreSQL

# Common target items database (same as production for RDS)
db.common-tgt-items.datasource.class=com.zaxxer.hikari.HikariDataSource
db.common-tgt-items.datasource.dataSourceClassName=org.postgresql.ds.PGSimpleDataSource
db.common-tgt-items.datasource.dataSourceProperties.serverName=${DB_HOST}
db.common-tgt-items.datasource.dataSourceProperties.portNumber=${DB_PORT}
db.common-tgt-items.datasource.dataSourceProperties.databaseName=${DB_NAME}
db.common-tgt-items.datasource.dataSourceProperties.user=${DB_USER}
db.common-tgt-items.datasource.dataSourceProperties.password=${DB_PASSWORD}
db.common-tgt-items.datasource.dataSourceProperties.ssl=false
db.common-tgt-items.datasource.maximumPoolSize=10
db.common-tgt-items.driver=org.postgresql.Driver
db.common-tgt-items.platform=PostgreSQL

# User profile database (RDS)
db.userprofile-production.datasource.class=com.zaxxer.hikari.HikariDataSource
db.userprofile-production.datasource.dataSourceClassName=org.postgresql.ds.PGSimpleDataSource
db.userprofile-production.datasource.dataSourceProperties.serverName=${DB_HOST}
db.userprofile-production.datasource.dataSourceProperties.portNumber=${DB_PORT}
db.userprofile-production.datasource.dataSourceProperties.databaseName=${DB_PROFILE_NAME}
db.userprofile-production.datasource.dataSourceProperties.user=${DB_USER}
db.userprofile-production.datasource.dataSourceProperties.password=${DB_PASSWORD}
db.userprofile-production.datasource.dataSourceProperties.ssl=false
db.userprofile-production.datasource.maximumPoolSize=10
db.userprofile-production.driver=org.postgresql.Driver
db.userprofile-production.platform=PostgreSQL

# ========================================
# RDS Performance Optimizations
# ========================================

# Increase batch sizes for RDS (network latency compensation)
intermine.batch.size=10000
intermine.bulk.load.batch.size=50000

# Optimize for RDS memory limits
os.query.max-time=1800000
os.query.max-limit=100000
os.query.max-offset=10000000

# Cache settings optimized for cloud
os.production.cache.size=500000
os.query.cache.size=100000

# Connection pool settings for RDS
db.production.datasource.connectionTimeout=60000
db.production.datasource.validationTimeout=30000
db.production.datasource.leakDetectionThreshold=300000

# ========================================
# Build-specific settings
# ========================================

# Environment markers
intermine.production.mode=true
intermine.ephemeral.build=true
intermine.rds.build=true

# Build timestamp
intermine.build.timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
intermine.build.instance=$(hostname)

EOF

    success "RDS properties file created"
}

# Function to copy properties to .intermine directory
copy_to_intermine_dir() {
    log "Copying properties to .intermine directory..."
    
    mkdir -p "$HOME/.intermine"
    cp "$PROPERTIES_FILE" "$INTERMINE_PROPERTIES"
    
    success "Properties copied to .intermine directory"
}

# Function to validate properties file
validate_properties() {
    log "Validating properties file..."
    
    # Check that required properties are present
    local required_props=(
        "db.production.datasource.dataSourceProperties.serverName"
        "db.production.datasource.dataSourceProperties.databaseName"
        "db.userprofile-production.datasource.dataSourceProperties.databaseName"
    )
    
    for prop in "${required_props[@]}"; do
        if ! grep -q "^$prop" "$PROPERTIES_FILE"; then
            error "Missing required property: $prop"
            return 1
        fi
    done
    
    # Verify database host is set correctly
    local db_host=$(grep "^db.production.datasource.dataSourceProperties.serverName" "$PROPERTIES_FILE" | cut -d'=' -f2)
    if [[ "$db_host" != "$DB_HOST" ]]; then
        error "Database host mismatch. Expected: $DB_HOST, Found: $db_host"
        return 1
    fi
    
    success "Properties file validation passed"
}

# Function to show configuration summary
show_configuration_summary() {
    log "=== Configuration Summary ==="
    log "Database Host: $DB_HOST:$DB_PORT"
    log "Main Database: $DB_NAME"
    log "Profile Database: $DB_PROFILE_NAME"
    log "Properties File: $PROPERTIES_FILE"
    log "InterMine Properties: $INTERMINE_PROPERTIES"
    log "Connection Pooling: Enabled (HikariCP)"
    log "SSL: Disabled (internal RDS)"
    log "Build Type: Ephemeral RDS Build"
    log "============================"
}

# Function to create connection test script
create_test_script() {
    log "Creating connection test script..."
    
    cat > "$HOME/test-rds-connection.sh" <<'EOF'
#!/bin/bash
# Test RDS connection script

set -euo pipefail

echo "🔍 Testing RDS Connection..."

# Test main database
echo "Testing main database connection..."
if psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME" -c "SELECT 'Main DB OK' as status;" 2>/dev/null; then
    echo "✅ Main database connection successful"
else
    echo "❌ Main database connection failed"
    exit 1
fi

# Test profile database
echo "Testing profile database connection..."
if psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DB_PROFILE_NAME" -c "SELECT 'Profile DB OK' as status;" 2>/dev/null; then
    echo "✅ Profile database connection successful"
else
    echo "❌ Profile database connection failed"
    exit 1
fi

# Show database sizes
echo "📊 Database Information:"
psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "postgres" -c "
SELECT 
    datname as database_name,
    pg_size_pretty(pg_database_size(datname)) as size,
    numbackends as active_connections
FROM pg_stat_database 
WHERE datname IN ('$DB_NAME', '$DB_PROFILE_NAME')
ORDER BY datname;
"

echo "🎉 All database connections successful!"
EOF

    chmod +x "$HOME/test-rds-connection.sh"
    success "Connection test script created: $HOME/test-rds-connection.sh"
}

# Main execution
main() {
    log "🔧 Configuring InterMine for RDS connection..."
    
    # Validate required environment variables
    if [[ -z "${DB_HOST:-}" ]] || [[ -z "${DB_USER:-}" ]] || [[ -z "${DB_PASSWORD:-}" ]]; then
        error "Required environment variables not set (DB_HOST, DB_USER, DB_PASSWORD)"
        exit 1
    fi
    
    # Set defaults
    DB_PORT=${DB_PORT:-5432}
    DB_NAME=${DB_NAME:-alliancemine_db}
    DB_PROFILE_NAME=${DB_PROFILE_NAME:-alliancemine_profiles_db}
    
    # Execute configuration steps
    backup_properties
    create_rds_properties
    copy_to_intermine_dir
    validate_properties
    create_test_script
    show_configuration_summary
    
    success "🎉 RDS configuration completed successfully!"
    
    return 0
}

# Run main function
main "$@"