-- Copy primaryidentifier to name + symbol on Chromosome rows that come out of
-- the FlyBase chado loader with NULL name/symbol attributes. Without this the
-- Query Builder + report pages show empty cells for `Chromosome > Name` and
-- `Chromosome > Symbol`, even though the underlying `primaryIdentifier` ("2L",
-- "3R", etc.) is populated and chromosomal locations resolve correctly.
--
-- RUN ORDER (see patch_attribute_fallbacks.sql for the full rationale):
--   Canonical: BEFORE `:dbmodel:postprocess`, so `create-attribute-indexes`
--   builds the chromosome name/symbol b-trees once over patched values.
--   Hot-fix on already-built DB: also safe, idempotent.
--   Always BEFORE `:webapp:summariseObjectStore` so the WAR's
--   `objectstoresummary.properties` reflects the patched chromosome attributes.
-- Idempotent — guarded by `WHERE … IS NULL`.
--
-- Usage:
--   PGPASSWORD=... psql -h <RDS_HOST> -U postgres -d <DB_NAME> \
--       -f patch_chromosome_names.sql
--
-- See docs/FLYMINE_DEPLOY_2026_06_05.md for the runtime context.
UPDATE chromosome SET name = primaryidentifier WHERE name IS NULL;
UPDATE chromosome SET symbol = primaryidentifier WHERE symbol IS NULL;
